name: 🌸 Build

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'doc/**'
      - '.editorconfig'
      - '.gitignore'
      - 'Copyright'
      - 'README.md'
      - 'RELEASE_NOTES'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'doc/**'
      - '.editorconfig'
      - '.gitignore'
      - 'Copyright'
      - 'README.md'
      - 'RELEASE_NOTES'

jobs:
  build:
    name: 🌸 Build
    runs-on: macos-14

    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
          
      - name: 🐧 set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10.1"
      
      - name: ☕️ set up JDK
        uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'zulu'
            cache: gradle

      - name: 🧬 Build
        env:
          scheme: ${{ 'default' }}
          DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer
        run: |
          make all

      - name: 🎊 Release Notes
        run: |
          echo "version_code=$(git rev-list --count HEAD)" >> $GITHUB_ENV
          echo "build_id=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo version_name="v1.0 $(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: 🎉 Publish Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          name: ${{ env.version_name }}
          tag_name: v1.0.${{ env.version_code }}
          make_latest: true
          files: |
            build/*.apk
            build/*.ipa
            build/*.aab